# Generated by Django 4.0.3 on 2022-03-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
    ]
