# Generated by Django 4.0.3 on 2022-04-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agendamento_executado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='executado',
        ),
    ]
